name: Checks and Tests
on: [push]

jobs:
  checks-unit-tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        run: npm install

      - name: Style and Typing Checks
        run: npm run check

      - name: Unit Tests
        run: npm run test:unit
        env:
          VITE_API_PREFIX: /api

  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          config: baseUrl=http://localhost:4173
          build: npm run build
          start: npm run preview
        env:
          VITE_API_PREFIX: /api

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore
